name: Endor Labs Scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  endorlabs-scan:
    permissions:
      id-token: write # This is required for requesting the JWT
      # security-events: write # Only needed for SARIF Output
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
      - name: Build 
        run: go build
      - name: Endor Labs Scan Push
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        uses: endorlabs/github-action@main
        with:
          namespace: "yolo"
          scan_summary_output_type: "table"
          ci_run: "false"
          enable_github_action_token: "true"
          sarif_file: endor-labs.sarif
          additional_args: "--enable=git,analytics,secrets"
      - name: Endor Labs Scan Push
        if: github.event_name == 'pull_request'
        uses: endorlabs/github-action@main
        with:
          namespace: "yolo"
          scan_summary_output_type: "table"
          ci_run: "false"
          enable_github_action_token: "true"
          sarif_file: endor-labs.sarif
          additional_args: "--enable=git,analytics,secrets --ci-baseline=main"
     # Use for to upload findings to GitHub.
     # - name: Upload SARIF to github
     #   if: github.event_name == 'push'
     #   uses: github/codeql-action/upload-sarif@9885f86fab4879632b7e44514f19148225dfbdcd
     #   with:
     #     sarif_file: endor-labs.sarif
